### ISSUE TITLE
Flightdeck model not found (on linux)

### ISSUE THREAD

**Issue by ghost** [HHS81/do328#12]
Hi!
Changing the path from 
		<path>Aircraft/do328/Models/Flightdeck.xml</path>
to
		<path>Aircraft/do328/Models/flightdeck.xml</path>
in the model .xml makes the flightdeck appearing also for linux users (which is very strict about correct lower/upper case).
LG

**Comment by xcvb85** [comment]
This is already fixed in issue10 branch + other improvements (e.g. basic eicas and working jet version). Maybe you can have a look.

**Comment by HHS81** [comment]
Fixed with merge of Issue10

**Comment by ghost** [comment]
Thanks!

Am 13.11.2016 um 13:26 schrieb HHS81:
