### ISSUE TITLE
jet version has no engine sounds

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#13]
Maybe we can get them from other aircraft but not sure which one.

**Comment by HHS81** [comment]
When I cleaned up the files for github, I simply forgot to add it. I still have the files, I will add them later today.

**Comment by HHS81** [comment]
Fix is in Issue#10 pull request

**Comment by xcvb85** [comment]
Fix is in Issue#11 pull request

**Comment by HHS81** [comment]
done
