### ISSUE TITLE
propellers wobble at startup

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#24]

**Comment by xcvb85** [comment]
Fix is in branch issue24. Please check if blade rotation is correct or if I made it worse (changed property to controls/engines/engine[0]/propeller-pitch).

**Comment by HHS81** [comment]
Unfortunately not the right property, since the propeller blade pitch depends on rpm and other factors, and already perferctly simulated by JSBSim.
The property already used or `fdm/jsbsim/propulsion/engine[n]/blade-angle` would be correct. I guess the error is inside the animation due to wrong axis/ center used.

**Comment by HHS81** [comment]
I guess just by using the correct center it should be fixed, I'll take a look at the weekend

**Comment by xcvb85** [comment]
I already fixed the wobbling propellers in issue24 branch but I used the wrong property afterwards.

**Comment by HHS81** [comment]
did you already changed the property?

**Comment by xcvb85** [comment]
Yes, have a look at my last commit (not sure about the blade offset angle). But the blande-angle only changes at higher rpms but then the blades are no longer shown.

**Comment by HHS81** [comment]
Hmm, sorry, no. The blades doesn't react correctly to the property.
But I maybe have an idea, why there are wobbling... 😄

**Comment by HHS81** [comment]
@xcvb85  I kept your values of the blade rogtate center in the animation, but changed the property to blade-angle. I don't see any wobbling, and in the sim the blade shows the corrrect values for being feathered.
Please take a look
