### ISSUE TITLE
strange edge in the near of 2nd passanger window

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#26]
Only in 328-110 (prop) version.

**Comment by HHS81** [comment]
I'take a look.

**Comment by ghost** [comment]
I guess that's the extra layer to prevent prop damage?

**Comment by ghost** [comment]
You can even see it a bit in this picture https://img.planespotters.net/photo/274000/original/hc-cfi-vuelos-internos-privados-vip-dornier-328-110_PlanespottersNet_274947.jpg

**Comment by xcvb85** [comment]
Yes you are right. But this extra layer seems to be very thin (just 5mm or so).

**Comment by HHS81** [comment]
Please see pull request #30
