### ISSUE TITLE
CDU not working

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#34]
@HHS81: I already got CDU from CitationX running but unfortunately I mixed things with EICAS. Please merge branch issue17 then I can commit the fix.

**Comment by HHS81** [comment]
issue17 merged

**Comment by xcvb85** [comment]
Fix is in branch issue34

**Comment by xcvb85** [comment]
@HHS81: If you wonder how to activate a route: In addition to the destination field you also must add your destination as last waypoint.

**Comment by HHS81** [comment]
@xcvb85 
Cool! Thanks!

But what I'm doing wrong?
When I added my destination as last waypoint and save the Flightplan I can't get any keys on the CDU working again. So I can't reach any other pages.

**Comment by xcvb85** [comment]
Saving is still an issue - so don't save it :wink: As soon as you entered the destination the plan is already activated and can be used. I know the CDU is not perfect and needs improvements but the issues also exists on the CitationX. I will create a new issue for that.

**Comment by HHS81** [comment]
Ah, I see. Just don't save it.... 😉
