### ISSUE TITLE
half rain bug

### ISSUE THREAD

**Issue by HHS81** [HHS81/do328#35]
half rain bug (rain appears only at one side)
fixable by changing the RMU-model to the one used by Pattens CitationX

**Comment by HHS81** [comment]
Hmm...no, not fiaxable with the Citations X RMU.... Needs converting to Canvas

**Comment by xcvb85** [comment]
It's the fault of the RMU? I will check it.

**Comment by xcvb85** [comment]
Good news: The problem is not the RMU but the MFD which I wanted to recreate with canvas anyway (required to show the EICAS system pages).

**Comment by xcvb85** [comment]
Even better news: There is already someone doing the job for me :grinning:
https://forum.flightgear.org/viewtopic.php?f=71&t=30534

**Comment by HHS81** [comment]
I wonder how the framerate will be ... Hooray's tips are always carefully to handle.

**Comment by xcvb85** [comment]
See pull request.

**Comment by xcvb85** [comment]
The improved CitationX was just released. I will check if we can use their MFD so maybe wait with merging this.

**Comment by HHS81** [comment]
I'll just check the Citation X. Looks great, framerates are also really nice. It just don't like to increase range on the ND-Map....And dimming the RMU as well.... With both things FGFS segfaults here.

**Comment by HHS81** [comment]
O.k. seems a prblem with the dev-versions. With FGFS 2016.4.2 it works like charme.

**Comment by xcvb85** [comment]
Can we close this?

**Comment by HHS81** [comment]
yes, and done!
