### ISSUE TITLE
too fast taxiing

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#39]
The slowest you can drive on the taxiway without braking all the time is about 70 knots which is quite quick.

**Comment by HHS81** [comment]
Pilot error! 😄 
And yes, it is a feature! :smile:

Like the real thing you need the throttle in beta range to taxi. This means you have to press Del-key. Now the range of the throttle control changes. Throttle control: 0=flight-idle to 1=max reverse. 
(works like in the dhc6!)
Pressing Del-key again changes back to flight state. This means Throttle control: 0=´flight idle to 1=max Power.

The only thing it lacks is the correct animation, and the simulation of the latch which prevents the throttle from reaching beta range in flight. 

Please see also Issue #7

**Comment by xcvb85** [comment]
Pilot error? :flushed:
