### ISSUE TITLE
PFD, MFD and EICAS screens are always on

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#43]
Not sure if they should just be black when switched off or if we should add reflections like on CitationX. I don't know if the screens are reflecting at all.

**Comment by HHS81** [comment]
we can add reflections later, when the flightdeck is really ready. I expect a bit reflections. The Dornier 328 seemed to have CRTs, with slight convex surface, covered with glass.

**Comment by HHS81** [comment]
Nice source: http://www.hasselbusch-esbeck.de/Fliegen/Do328/start.htm

**Comment by xcvb85** [comment]
Sure, reflections are low priority. I just wanted to know if a funtionality for the screen is required to go black or if there will be a layer for reflections anyway located on top of the canvas layer (hidden if device is switched on).

**Comment by HHS81** [comment]
ah, to go black you need to animate the material of the screen which is linked to the canvas. It would work like the CDU brightness. I think we though need an layer for reflections.

**Comment by xcvb85** [comment]
@HHS81: Solution is in branch issue17. Please let me know if you like it.

**Comment by xcvb85** [comment]
Can we close this now?

**Comment by HHS81** [comment]
Yep, I think it looks o.k. Maybe we can change it later to interior reflection like the c172p guys did. But really for later.
