### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by xcvb85** [HHS81/do328#59]
Something like this is what I had in mind:
![splash](http://i64.tinypic.com/ir0w76.png)
Please let me know if you like it or if you have a better idea.

**Comment by ghost** [comment]
@xcvb85 how do you make this smooth transition from solid to wireframe? In blender? 
(and btw, I would leave out the lights, they kinda spoil the great visuals ;))

**Comment by HHS81** [comment]
Wow, cool! 😮 
Gimp? Photoshop?

Yes, I think, the light quads are distracting, otherwise it looks really cool! I like it!

**Comment by xcvb85** [comment]
I rendered two images in blender (wireframe and solid) and did the post processing in gimp. In gimp you can define a layer mask (right click on layer) and then use gradient (button l) as mask. This was just quick and dirty image to show the general idea (also front wheel and right wing are missing). In this way the propeller or the jet engine are highlighted.

**Comment by xcvb85** [comment]
This is what I got so far:

![splash](http://i66.tinypic.com/2d9nts6.png)

In the box I would put some information like speed, range, service ceiling (in metric units). What do you think?

**Comment by HHS81** [comment]
Looks Great! 😮 

 What looks a bit strange is the closed gear doors. Maybe removing the landing gear is an better option.
I would change the title into  _Dornier 328-JET_  since there is a -300 and a -310. 

Otherwise it looks really great, and to put the information in the box is a relly great idea!

**Comment by xcvb85** [comment]
The gear doors was my fault. Now I know how they work. I will open a new issue to clarify how the naming of the different types should be.
